#!/bin/bash
# The Raven Linux logo, into a sysroot.
#
# /etc/os-release says `LOGO=raven-logo`, which is an icon-theme name: anything
# that shows "the logo of this OS" -- the Settings About page, the Store and
# Power mastheads, the installer's welcome page, a fastfetch -- asks the icon
# theme for `raven-logo` and gets whatever hicolor has under that name. Until
# this existed, nothing was under that name and every one of those places fell
# back to a generic symbolic icon.
#
# Two names are installed:
#
#   raven-logo        light body on the purple wing: for the dark ground every
#                     Raven surface has (Raven Glass is #16161f everywhere)
#   raven-logo-dark   the artwork as drawn, black body: for a light ground
#
# Both come from branding/ at the repository root; the PNG ladder under
# branding/sizes/ is generated by scripts/branding/render-logo.py and must not
# be edited by hand. Sourced by stage2-native.sh and stage-gui.sh.

# install_raven_branding SYSROOT
#
# Idempotent: every copy is `install`, so a GUI-only rebuild over an older
# sysroot lands the same files as a full build.
install_raven_branding() {
    local sysroot="$1"
    local branding="${PROJECT_ROOT}/branding"
    local icons="${sysroot}/usr/share/icons/hicolor"

    if [[ ! -f "${branding}/raven-logo-light.png" ]]; then
        log_warn "  no ${branding}/raven-logo-light.png: LOGO=raven-logo will resolve to nothing"
        return 0
    fi

    # Scalable: the SVG wrappers. Raster inside, but hicolor's scalable/ is
    # where GTK looks first for an icon it will draw at an arbitrary size.
    install -Dm 0644 "${branding}/raven-logo-light.svg" "${icons}/scalable/apps/raven-logo.svg"
    install -Dm 0644 "${branding}/raven-logo.svg" "${icons}/scalable/apps/raven-logo-dark.svg"

    # The fixed sizes, for anything that prefers a bitmap at its own size.
    local size
    for size in 16 22 24 32 48 64 96 128 256 512; do
        [[ -f "${branding}/sizes/raven-logo-light-${size}.png" ]] || continue
        install -Dm 0644 "${branding}/sizes/raven-logo-light-${size}.png" \
            "${icons}/${size}x${size}/apps/raven-logo.png"
        install -Dm 0644 "${branding}/sizes/raven-logo-${size}.png" \
            "${icons}/${size}x${size}/apps/raven-logo-dark.png"
    done

    # pixmaps is the pre-icon-theme lookup path that os-release consumers
    # (and anything old) still check. One size, a plain PNG.
    install -Dm 0644 "${branding}/sizes/raven-logo-light-256.png" "${sysroot}/usr/share/pixmaps/raven-logo.png"
    install -Dm 0644 "${branding}/raven-logo-light.svg" "${sysroot}/usr/share/pixmaps/raven-logo.svg"

    # The icon cache, if the build host can rebuild it; GTK falls back to
    # scanning the directories when the cache is stale, so this is speed only.
    if command -v gtk4-update-icon-cache >/dev/null 2>&1; then
        gtk4-update-icon-cache -q -t -f "${icons}" 2>/dev/null || true
    elif command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t -f "${icons}" 2>/dev/null || true
    fi

    log_info "  Installed raven-logo into ${icons}"
}
